const keys = [
    "_appTitle",
    "connectToPm2",
    "noContentToShow",
    "noProcessInList",
    "type",
    "port",
    "protocol",
    "hostname",
    "connect",
    "disconnect",
    "start",
    "restart",
    "stop",
    "flush",
    "reset",
    "flushAll",
    "resetAll",
    "refresh",
    "autoRefresh",
    "cpuPercentage",
    "memoryMegabyteUsage",
    "succeeded",
    "connectFailed",
    "unknown",
    "unknownError",
    "token",
    "invalidToken",
    "history",
    "clear",
    "log",
    "readonlyMode",
    "fieldIsRequired",
    "minValidValue",
    "maxValidValue",
    "minValidLength",
    "maxValidLength",
    "validLength",
    "login",
    "username",
    "password",
    "return",

    "createUser",
    "edit",
    "editUser",
    "repeatPassword",
    "accountType",
    "adminAccountTypeDescription",
    "managerAccountTypeDescription",
    "memberAccountTypeDescription",
    "processPermissions",
    "addProcess",
    "processName",
    "permissions",
    "view",
    "delete",
    "viewOutputLog",
    "viewErrorLog",
    "activate",
    "deactivate",
    "rowsSelected",
    "restarts",
    "uptime",

    "submit",
    "save",
    "search",
    "dashboard",
    "users",
    "active",
    "inactive",
    "status",
    "failed",
    "close",
    "none",
    "name",
    "stopAll",
    "operation",
    "serverDidNotRespondHello",
    "noAccess",
    "nonOkResponse",
    "downloadFailed",
    "getListFailed",
    "couldNotGetFilePath",
    "couldNotReaFileData",
    "usernameTaken",
    "couldNtHashPassword",
    "userNotFound",
    "adminEditForbidden",
    "invalidCredential",
    "serverVersionDoesNotMatch"
] as const;

export type UITextKey = typeof keys[number];

export type UITextKeyOptional = UITextKey | (string & {});

export type UITextType = {
    [Key in UITextKey]: string;
};
